//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore.Products.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetStore.Products.Application.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryAlreadyExists.
        /// </summary>
        internal static string CategoryAlreadyExists {
            get {
                return ResourceManager.GetString("CategoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryIsNotFound.
        /// </summary>
        internal static string CategoryIsNotFound {
            get {
                return ResourceManager.GetString("CategoryIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescriptionNotFound.
        /// </summary>
        internal static string DescriptionNotFound {
            get {
                return ResourceManager.GetString("DescriptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorAllTegs.
        /// </summary>
        internal static string ErrorAllTegs {
            get {
                return ResourceManager.GetString("ErrorAllTegs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCreateCategory.
        /// </summary>
        internal static string ErrorCreateCategory {
            get {
                return ResourceManager.GetString("ErrorCreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCreateDescription.
        /// </summary>
        internal static string ErrorCreateDescription {
            get {
                return ResourceManager.GetString("ErrorCreateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCreateProduct.
        /// </summary>
        internal static string ErrorCreateProduct {
            get {
                return ResourceManager.GetString("ErrorCreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCreateProductInCategory.
        /// </summary>
        internal static string ErrorCreateProductInCategory {
            get {
                return ResourceManager.GetString("ErrorCreateProductInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCreateProductPassport.
        /// </summary>
        internal static string ErrorCreateProductPassport {
            get {
                return ResourceManager.GetString("ErrorCreateProductPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorDeleteCategory.
        /// </summary>
        internal static string ErrorDeleteCategory {
            get {
                return ResourceManager.GetString("ErrorDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorDeleteDescription.
        /// </summary>
        internal static string ErrorDeleteDescription {
            get {
                return ResourceManager.GetString("ErrorDeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorDeleteProduct.
        /// </summary>
        internal static string ErrorDeleteProduct {
            get {
                return ResourceManager.GetString("ErrorDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorDeleteProductInCategory.
        /// </summary>
        internal static string ErrorDeleteProductInCategory {
            get {
                return ResourceManager.GetString("ErrorDeleteProductInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorDeleteProductPassport.
        /// </summary>
        internal static string ErrorDeleteProductPassport {
            get {
                return ResourceManager.GetString("ErrorDeleteProductPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorGetAllProduct.
        /// </summary>
        internal static string ErrorGetAllProduct {
            get {
                return ResourceManager.GetString("ErrorGetAllProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorGetAllProductsInCategory.
        /// </summary>
        internal static string ErrorGetAllProductsInCategory {
            get {
                return ResourceManager.GetString("ErrorGetAllProductsInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorGetCategory.
        /// </summary>
        internal static string ErrorGetCategory {
            get {
                return ResourceManager.GetString("ErrorGetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorGetDescription.
        /// </summary>
        internal static string ErrorGetDescription {
            get {
                return ResourceManager.GetString("ErrorGetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorGetProduct.
        /// </summary>
        internal static string ErrorGetProduct {
            get {
                return ResourceManager.GetString("ErrorGetProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorDeleteProductInCategory.
        /// </summary>
        internal static string ErrorGetProductInCategory {
            get {
                return ResourceManager.GetString("ErrorGetProductInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorGetProductPassport.
        /// </summary>
        internal static string ErrorGetProductPassport {
            get {
                return ResourceManager.GetString("ErrorGetProductPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorTegCreate.
        /// </summary>
        internal static string ErrorTegCreate {
            get {
                return ResourceManager.GetString("ErrorTegCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorTegDelete.
        /// </summary>
        internal static string ErrorTegDelete {
            get {
                return ResourceManager.GetString("ErrorTegDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorTegGet.
        /// </summary>
        internal static string ErrorTegGet {
            get {
                return ResourceManager.GetString("ErrorTegGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorTegUpdate.
        /// </summary>
        internal static string ErrorTegUpdate {
            get {
                return ResourceManager.GetString("ErrorTegUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorUpdateCategory.
        /// </summary>
        internal static string ErrorUpdateCategory {
            get {
                return ResourceManager.GetString("ErrorUpdateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorUpdateDescription.
        /// </summary>
        internal static string ErrorUpdateDescription {
            get {
                return ResourceManager.GetString("ErrorUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorUpdateProduct.
        /// </summary>
        internal static string ErrorUpdateProduct {
            get {
                return ResourceManager.GetString("ErrorUpdateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorUpdateProductInCategory.
        /// </summary>
        internal static string ErrorUpdateProductInCategory {
            get {
                return ResourceManager.GetString("ErrorUpdateProductInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorUpdateProductPassport.
        /// </summary>
        internal static string ErrorUpdateProductPassport {
            get {
                return ResourceManager.GetString("ErrorUpdateProductPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductAlreadyExists.
        /// </summary>
        internal static string ProductAlreadyExists {
            get {
                return ResourceManager.GetString("ProductAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductIsNotFound.
        /// </summary>
        internal static string ProductIsNotFound {
            get {
                return ResourceManager.GetString("ProductIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductPassportAlreadyExists.
        /// </summary>
        internal static string ProductPassportAlreadyExists {
            get {
                return ResourceManager.GetString("ProductPassportAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductPassportNotFound.
        /// </summary>
        internal static string ProductPassportNotFound {
            get {
                return ResourceManager.GetString("ProductPassportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TegAlreadyExists.
        /// </summary>
        internal static string TegAlreadyExists {
            get {
                return ResourceManager.GetString("TegAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TegIsNotFound.
        /// </summary>
        internal static string TegIsNotFound {
            get {
                return ResourceManager.GetString("TegIsNotFound", resourceCulture);
            }
        }
    }
}
