//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore.Users.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetStore.Users.Application.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressAlreadyExists.
        /// </summary>
        public static string AddressAlreadyExists {
            get {
                return ResourceManager.GetString("AddressAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressNotFound.
        /// </summary>
        public static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CartNotExist.
        /// </summary>
        public static string CartNotExist {
            get {
                return ResourceManager.GetString("CartNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalServerException.
        /// </summary>
        public static string InternalServerException {
            get {
                return ResourceManager.GetString("InternalServerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidClientRequrest.
        /// </summary>
        public static string InvalidClientRequrest {
            get {
                return ResourceManager.GetString("InvalidClientRequrest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidToken.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItIsNotPossibleToSpecifyCity.
        /// </summary>
        public static string ItIsNotPossibleToSpecifyCity {
            get {
                return ResourceManager.GetString("ItIsNotPossibleToSpecifyCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItIsNotPossibleToSpecifyStreet.
        /// </summary>
        public static string ItIsNotPossibleToSpecifyStreet {
            get {
                return ResourceManager.GetString("ItIsNotPossibleToSpecifyStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassportNotValid.
        /// </summary>
        public static string PassportNotValid {
            get {
                return ResourceManager.GetString("PassportNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordNotMatch.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductAlreadyExists.
        /// </summary>
        public static string ProductAlreadyExists {
            get {
                return ResourceManager.GetString("ProductAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductNotFound.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductNotFoundInCart.
        /// </summary>
        public static string ProductNotFoundInCart {
            get {
                return ResourceManager.GetString("ProductNotFoundInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleAlreadyExists.
        /// </summary>
        public static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleNotFound.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheSpecifiedCountryCannotBeEntered.
        /// </summary>
        public static string TheSpecifiedCountryCannotBeEntered {
            get {
                return ResourceManager.GetString("TheSpecifiedCountryCannotBeEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheSpecifiedRegionCannotBeEntered.
        /// </summary>
        public static string TheSpecifiedRegionCannotBeEntered {
            get {
                return ResourceManager.GetString("TheSpecifiedRegionCannotBeEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAlreadyExists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotFound.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRoleAlreadyExists.
        /// </summary>
        public static string UserRoleAlreadyExists {
            get {
                return ResourceManager.GetString("UserRoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRoleNotFound.
        /// </summary>
        public static string UserRoleNotFound {
            get {
                return ResourceManager.GetString("UserRoleNotFound", resourceCulture);
            }
        }
    }
}
