//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore.Markets.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetStore.Markets.Application.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressAlreadyExists.
        /// </summary>
        public static string AddressAlreadyExists {
            get {
                return ResourceManager.GetString("AddressAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressCreateError.
        /// </summary>
        public static string AddressCreateError {
            get {
                return ResourceManager.GetString("AddressCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressDeleteError.
        /// </summary>
        public static string AddressDeleteError {
            get {
                return ResourceManager.GetString("AddressDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressNotFound.
        /// </summary>
        public static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressUpdateError.
        /// </summary>
        public static string AddressUpdateError {
            get {
                return ResourceManager.GetString("AddressUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeAlreadyExists.
        /// </summary>
        public static string EmployeAlreadyExists {
            get {
                return ResourceManager.GetString("EmployeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeCreateError.
        /// </summary>
        public static string EmployeCreateError {
            get {
                return ResourceManager.GetString("EmployeCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeDeleteError.
        /// </summary>
        public static string EmployeDeleteError {
            get {
                return ResourceManager.GetString("EmployeDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeNotFound.
        /// </summary>
        public static string EmployeNotFound {
            get {
                return ResourceManager.GetString("EmployeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployePassportAlreadyExists.
        /// </summary>
        public static string EmployePassportAlreadyExists {
            get {
                return ResourceManager.GetString("EmployePassportAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployePassportCreateError.
        /// </summary>
        public static string EmployePassportCreateError {
            get {
                return ResourceManager.GetString("EmployePassportCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployePassportDeleteError.
        /// </summary>
        public static string EmployePassportDeleteError {
            get {
                return ResourceManager.GetString("EmployePassportDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployePassportNotFound.
        /// </summary>
        public static string EmployePassportNotFound {
            get {
                return ResourceManager.GetString("EmployePassportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployePassportUpdateError.
        /// </summary>
        public static string EmployePassportUpdateError {
            get {
                return ResourceManager.GetString("EmployePassportUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeUpdateError.
        /// </summary>
        public static string EmployeUpdateError {
            get {
                return ResourceManager.GetString("EmployeUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalServerException.
        /// </summary>
        public static string InternalServerException {
            get {
                return ResourceManager.GetString("InternalServerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketAlreadyExists.
        /// </summary>
        public static string MarketAlreadyExists {
            get {
                return ResourceManager.GetString("MarketAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketCapitalAlreadyExists.
        /// </summary>
        public static string MarketCapitalAlreadyExists {
            get {
                return ResourceManager.GetString("MarketCapitalAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketCapitalCreateError.
        /// </summary>
        public static string MarketCapitalCreateError {
            get {
                return ResourceManager.GetString("MarketCapitalCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketCapitalDeleteError.
        /// </summary>
        public static string MarketCapitalDeleteError {
            get {
                return ResourceManager.GetString("MarketCapitalDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketCapitalNotFound.
        /// </summary>
        public static string MarketCapitalNotFound {
            get {
                return ResourceManager.GetString("MarketCapitalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketCapitalUpdateError.
        /// </summary>
        public static string MarketCapitalUpdateError {
            get {
                return ResourceManager.GetString("MarketCapitalUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketCreateError.
        /// </summary>
        public static string MarketCreateError {
            get {
                return ResourceManager.GetString("MarketCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketDeleteError.
        /// </summary>
        public static string MarketDeleteError {
            get {
                return ResourceManager.GetString("MarketDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketNotFound.
        /// </summary>
        public static string MarketNotFound {
            get {
                return ResourceManager.GetString("MarketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketUpdateError.
        /// </summary>
        public static string MarketUpdateError {
            get {
                return ResourceManager.GetString("MarketUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassportAlreadyExists.
        /// </summary>
        public static string PassportAlreadyExists {
            get {
                return ResourceManager.GetString("PassportAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassportCreateError.
        /// </summary>
        public static string PassportCreateError {
            get {
                return ResourceManager.GetString("PassportCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassportDeleteError.
        /// </summary>
        public static string PassportDeleteError {
            get {
                return ResourceManager.GetString("PassportDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassportNotFound.
        /// </summary>
        public static string PassportNotFound {
            get {
                return ResourceManager.GetString("PassportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassportUpdateError.
        /// </summary>
        public static string PassportUpdateError {
            get {
                return ResourceManager.GetString("PassportUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordIsNotValid.
        /// </summary>
        public static string PasswordIsNotValid {
            get {
                return ResourceManager.GetString("PasswordIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductAlreadyExists.
        /// </summary>
        public static string ProductAlreadyExists {
            get {
                return ResourceManager.GetString("ProductAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductCreateError.
        /// </summary>
        public static string ProductCreateError {
            get {
                return ResourceManager.GetString("ProductCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductDeleteError.
        /// </summary>
        public static string ProductDeleteError {
            get {
                return ResourceManager.GetString("ProductDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductLineAlreadyExists.
        /// </summary>
        public static string ProductLineAlreadyExists {
            get {
                return ResourceManager.GetString("ProductLineAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductLineCreateError.
        /// </summary>
        public static string ProductLineCreateError {
            get {
                return ResourceManager.GetString("ProductLineCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductLineDeleteError.
        /// </summary>
        public static string ProductLineDeleteError {
            get {
                return ResourceManager.GetString("ProductLineDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductLineNotFound.
        /// </summary>
        public static string ProductLineNotFound {
            get {
                return ResourceManager.GetString("ProductLineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductLineUpdateError.
        /// </summary>
        public static string ProductLineUpdateError {
            get {
                return ResourceManager.GetString("ProductLineUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductNotFound.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductUpdateError.
        /// </summary>
        public static string ProductUpdateError {
            get {
                return ResourceManager.GetString("ProductUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAlreadyExists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCreateError.
        /// </summary>
        public static string UserCreateError {
            get {
                return ResourceManager.GetString("UserCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDeleteError.
        /// </summary>
        public static string UserDeleteError {
            get {
                return ResourceManager.GetString("UserDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotFound.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserUpdateError.
        /// </summary>
        public static string UserUpdateError {
            get {
                return ResourceManager.GetString("UserUpdateError", resourceCulture);
            }
        }
    }
}
